apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: squidy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: squidy
    spec:
      containers:
        - name: squidy
          image: tibbar/squidy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4180
          volumeMounts:
            - name: configuration
              mountPath: /conf

      volumes:
        - name: configuration
          configMap:
            name: conf
