apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oauth2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth2
    spec:
      containers:
        - name: oauth2
          image: tibbar/kubernetes-oauth2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4180
          volumeMounts:
            - name: configuration
              mountPath: /conf

      volumes:
        - name: configuration
          configMap:
            name: conf
